name: multimodal_decoding
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - notebook
  - tensorboard
  - matplotlib
  - nipype
  - cpuonly
  - torchvision
  - pytorch
  - tqdm
  - scikit-learn
  - transformers
  - pandas
  - tokenizers
